### ISSUE TITLE
Unified bank account

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#1]
Demande originale : 
On met de l'argent sur le portail, et chaque assoce peut piocher dedans l'élève achète qqc : biero, ticket bda, pain de mine, freshbox, etc

**Comment by abocquet** [comment]
I talked about it to the BDE treasurer the other day. He isn't very enthusiastic considering that HE would have to make every money transfer from the BDE account to the clubs' account.

We could tackle this issue by making the banking system clever : when someone wants to put money on it's global bank account, the application determines to which account the money should be wired so as to balance the money between associations.

For instance :
- Everyone starts with 0€ 
- Alice buy a tomato juice to Octo for 2€
- Alice buy 3 baguettes for 3€ to Pain de Mine
- Bob adds 5€. The system redirect him to Pain de Mine's Pumpkin page, because it is the most in the negative
- Alice wants to pay her debts, she add 5€. This time the system redirects her to Octo for the same reason.

This seems a little complicated and must be bullet-proof before we use it in prod, but it would be a real improvement of the current system. We also have to provide some money reserves to these associations, but that's (also) why the PCV exists.

**Comment by 14roiron** [comment]
A huge discussion need to be done, do we really want a public website to manage cash from the user?
We've already seen that we could be attacked, 
If we do that, we need a plan, if the database is corrupted, what should we do?
That's why the current system is stored offline and is read-only from the internet!

**Comment by Piwakk** [comment]
@abocquet 
Looks like we are not on the way of implementing a unified bank account (and maybe it's for the best).

However, the concern raised by 14roiron is still valid. What do you think about it?
