### ISSUE TITLE
Student forum

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#10]

**Comment by garbadrom** [comment]
Pour qu’il puisse y avoir des discussions et des avis sur les cours/options, des débats politiques ou non, des bons plans, etc. Attention à ne pas oublier de mettre une option pour cacher des thèmes aux 1A avant le baptême. Une première version fonctionnelle a déjà été codée (mais pas encore mergée) dans l'ancienne version du portail, on peut donc s'en inspirer/la copier.

**Comment by abocquet** [comment]
First iteration has been merged on master. The following improvement could be nice
- [ ] voting for good answers (like StackOverflow)
- [ ] possibility to sort answers by vote or date
- [ ] admin functionalities (create topic...)

Add your suggestions !

**Comment by abocquet** [comment]
I first version has been release by @Maxence-Leroy, some improvement can be made (lock thread, edit answer...) but it's good enough for a first release
