### ISSUE TITLE
Missing step in 'Setting up project locally'

### ISSUE THREAD

**Issue by theophilec** [Mines-Paristech-Students/Portail-des-eleves#128]
Missing step in [Setting up project locally](https://github.com/Mines-Paristech-Students/Portail-des-eleves/wiki/Setting-up-the-project-locally#backend) in the project Wiki. 

One needs to `./cli/create_and_populate_database.bash` on Linux (and equivalent `.bat` on Windows).

**Comment by theophilec** [comment]
No problem @abocquet. I'll patch the wiki!

**Comment by abocquet** [comment]
Also add the url to authenticate

**Comment by theophilec** [comment]
> Also add the url to authenticate

Good point

**Comment by theophilec** [comment]
Should be ok. Closing this issue.
