### ISSUE TITLE
Tabler.io problems

### ISSUE THREAD

**Issue by MartinBriand** [Mines-Paristech-Students/Portail-des-eleves#144]
It looks like tabler.io has many issues we should correct before pushing our website online, even if it is not critical though.

* Double cross for Bootsrtap's Alert or Modal
* Form invalid css style "invalid-feedback" has to be wraped in an "is-invalid input-group" className

**Comment by abocquet** [comment]
The first issue is indeed a glitch, it should be easily fixed in tabler.
On the second point, I'm not sure what you mean, `.invalid-feedback` is not necessarily wrapped into `.is-invalid .input-group` in tabler's docs:

```html
<div class="form-group">
    <label class="form-label">Invalid State</label>
    <input type="text" class="form-control is-invalid" name="example-text-input-invalid" placeholder="Invalid State..">
    <div class="invalid-feedback">Invalid feedback</div>
    <input type="text" class="form-control mt-3 state-invalid" value="Invalid state">
</div>
```
https://preview.tabler.io/form-elements.html

**Comment by Piwakk** [comment]
Double cross was corrected, as well as the invalid feedback (display: block was the solution)
