### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#15]
Peu ou prou celui qui existe actuellement.
Que pensez vous de le mettre en fenêtre flottante en bas, style Facebook ?

**Comment by garbadrom** [comment]
Je suis plutôt d'avis de garder le même format qu'actuellement (les fenêtres fb qui s'ouvrent automatiquement et qui cachent des trucs, perso ça m'énerve).

En théorie on pourrait aussi donner la possibilité aux gens de créer des "chatrooms", mais ça serait un petit bazar à gérer, et le fait d'avoir un forum va déjà permettre de séparer les discussions selon le sujet.

**Comment by abocquet** [comment]
C'est un peu relou d'avoir le chat a en haut a droite de la page, on peut pas trop naviguer et le consulter en même temps.
S'il pouvait être fixé en bas à droite ce serait quand même plus pratique (un peu comme sur Facebook) et le fait qu'il soit retractable éviterait qu'on ait a le scroller sur chaque page qu'on charge sur mobile
