### ISSUE TITLE
Profil section

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#16]
Peu ou prou la page de profil de la V1, avec
- [x] filiation 
- [ ] option
- [ ] questions de personnalité 
- [x] chambre (avec option PAM)
- [x] numéro de téléphone 
- [ ] associations
- [ ] instruments

**Comment by garbadrom** [comment]
Ce serait bien d'ajouter la possibiltié de rentrer un parrain/marraine qui est 2 promos au dessus, pour les redoublants ! (donc ne pas restreindre le choix à la promo n+1)
