### ISSUE TITLE
Palums

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#20]
Peu ou prou comme dans la V1

**Comment by garbadrom** [comment]
À noter que le BDE n'est pas la seule assoc à uploader des pdf sur le portail (coucou le Vendôme et l'abatage).
Il sera donc probablement plus pratique de faire un système général pour toutes les assoc (go #12 ). Peut être que ça pourrait quand même être sympa de faire un truc plus personnalisé pour le tri des palums qu'une simple liste (tri par promo ou par année), mais c'est pas urgent, je pense qu'on peut fermer l'issue pour l'instant.
