### ISSUE TITLE
Sidebar checkboxes of a same section should be ORs, not ANDs

### ISSUE THREAD

**Issue by Piwakk** [Mines-Paristech-Students/Portail-des-eleves#208]
Sidebar checkboxes of a same section are currently doing an AND. However, the user expects it to do an OR on the conditions.

Currently:

![image](https://user-images.githubusercontent.com/11032610/83326398-01e65600-a274-11ea-8c06-ea52cf32e151.png)

But for instance in this website:

![image](https://user-images.githubusercontent.com/11032610/83326412-1e828e00-a274-11ea-81ec-5e741cb3cbfd.png)

**Comment by abocquet** [comment]
Does they?
