### ISSUE TITLE
Classrooms availability

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#21]
- [ ] affichage des disponibilités des salles
- [ ] possiblité de réserver une salle (au lieu de devoir remplir le form sur marjolaine)

**Comment by garbadrom** [comment]
Je suis plutôt d'avis de garder le système actuel (en ajoutant la possibilité d'afficher les disponibilités d'autres jours). Refaire le form de marjolaine risque d'être compliqué pour pas grand chose (même s'il n'utilise pas de CSS, il marche déjà, et ce n'est même pas notre domaine, pas sur qu'il y ait un API bien pratique)

**Comment by abocquet** [comment]
Encore une fois, avec un peu de parsage on peut faire des merveilles

**Comment by abocquet** [comment]
This functionality is now available on Oasis
