### ISSUE TITLE
Cross-routers links do not work (at least not as expected)

### ISSUE THREAD

**Issue by Piwakk** [Mines-Paristech-Students/Portail-des-eleves#232]
Checkout the branch `linkBug`

Go to http://localhost:3000/trombi, http://localhost:3000/associations/bde or http://localhost:3000/sondages and try to click on the big links. Left-clicking will sometimes yield a 404. Opening in a new tab will work though.

It looks like only the links contained in children of `AssociationRouter` or `PollsRouter` are affected.

**Comment by abocquet** [comment]
Fixed in #245
