### ISSUE TITLE
When switching tabs, the checkboxes uncheck themselves (but the filter is still applied)

### ISSUE THREAD

**Issue by Piwakk** [Mines-Paristech-Students/Portail-des-eleves#240]
When I select tags then switch tabs, the checkboxes uncheck themselves (but the filter is still applied).

Before switching tab:
![image](https://user-images.githubusercontent.com/11032610/83925974-cf16f300-a788-11ea-854e-a7ad9a8782d0.png)

After:
![image](https://user-images.githubusercontent.com/11032610/83925984-d6d69780-a788-11ea-9dfa-c4ebe1783b7a.png)

_Originally posted by @Piwakk in https://github.com/Mines-Paristech-Students/Portail-des-eleves/pull/229#issuecomment-639849899_

**Comment by abocquet** [comment]
Fixed in #230
