### ISSUE TITLE
Pain de Mine interface

### ISSUE THREAD

**Issue by Maxence-Leroy** [Mines-Paristech-Students/Portail-des-eleves#3]
Faire une interface plus user friendly : blocage à une certaine heure, préciser jour précis plutôt que jour de la semaine, etc.

**Comment by garbadrom** [comment]
Dans le même esprit (mais avec moins de choix), freshbox aimerait également une interface utilisateur pour commander les freshbox (au lieu de le faire par form), et une interface admin pour gérer ces commandes (affichage/exportation/modification des soldes, importation des soldes pumpkins depuis un excel, gestion des commandes, etc)

**Comment by abocquet** [comment]
Replaced by #30
