### ISSUE TITLE
[Election] Error when trying to delete

### ISSUE THREAD

**Issue by delmaass** [Mines-Paristech-Students/Portail-des-eleves#346]
An error occurs when I try to delete an election. Here the election was not ended. Can't be deleted.

![image](https://user-images.githubusercontent.com/20560223/161846057-d5730500-1147-4b95-8ac0-0802601d4167.png)

**Comment by alexianelaude** [comment]
<img width="630" alt="Screenshot 2022-04-07 at 8 53 57 PM" src="https://user-images.githubusercontent.com/45003997/162276205-3272592a-a2ed-45f1-b7b1-9f8c4b7b6c8e.png">

This seems to be expected, not sure if such a rule is useful though. In any case [this PR](https://github.com/Mines-Paristech-Students/Portail-des-eleves/pull/353) fixes the error message

**Comment by abocquet** [comment]
It's not a bug but the error message is not explicative at all, maybe this should be an issue
