### ISSUE TITLE
Using password salt

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#36]
In order to take no chance with passwords, we could both:
- add an app salt to encrypt password, so if the database is compromised but not the code, the passwords are safe
- add a user-unique salt generated randomly, so even if the database AND the source code are compromised it would be still computationally too expensive to crack them all. In a word, it prevents the use of a rainbow table

**Comment by garbadrom** [comment]
By default, Django already uses use-unique salts : https://docs.djangoproject.com/en/2.0/topics/auth/passwords/.

Encrypting password ourselves could be an option, but it would require messing around with django default `auth` code and I'm not a huge fan of that.
