### ISSUE TITLE
Integrating BDA

### ISSUE THREAD

**Issue by Maxence-Leroy** [Mines-Paristech-Students/Portail-des-eleves#4]
Voir avec le bureau du BDA pour intégrer une partie des fonctionnalités du site du BDA sur le portail

**Comment by garbadrom** [comment]
C'est ça, ils aimeraient pouvoir faire des sondages pour avoir une idée du nb de personnes intéressées par chaque spectacle. Ils peuvent même peut être nous fournir qqn de motivé pour le faire (Victor Vialard).
On pourrait réfléchir, potentiellement, à intégrer le site du BDA sur le portail à terme s'ils veulent, mais là ce n'est plus du tout une priorité (ils ont quand même un site avec une billetterie qui marche).
