### ISSUE TITLE
Mediamines Interfaces

### ISSUE THREAD

**Issue by Maxence-Leroy** [Mines-Paristech-Students/Portail-des-eleves#5]
Améliorer l'affichage des galeries, rajouter un système pour encourager les gens à identifier, rajouter fonctionnalités plus "réseau social".

**Comment by abocquet** [comment]
On pourrait essayer de faire ça pour toutes les associations non ?

**Comment by Maxence-Leroy** [comment]
Oui, mais il y a des trucs à faire en plus avec les photos

**Comment by abocquet** [comment]
Comme quoi ? On pourrait permettre aux gens d'identifier les personnes sur les photos de toutes les assos non ?

**Comment by Maxence-Leroy** [comment]
En général les autres assos ne postent que très peu de photos. Par exemple, même les photos Trium sont gérées par Mediamines je crois.

**Comment by abocquet** [comment]
Certes, mais ça ne coute pas plus cher de permettre à tout le monde de le faire. Au pire, si on insère les galleries dans une espèce de flux d'actualité de l'association, si les asso ne publient pas, ça ne se verra pas 🙂

**Comment by garbadrom** [comment]
Y'a quand même un truc particulier avec les galeries MédiaMines, c'est qu'un service de tirage photo est proposé (d'où l'intérêt des identifications et des likes). Il faudra donc :
- (re)faire l'interface admin pour que médiamines puisse gérer ces commandes de photos
- (re)faire l'interface utilisateur permettant de commander ces photos. Ce serait cool d'avoir la possibilité de faire sa liste de voeux, puis d'appuyer sur un bouton "effectuer la commande" quand on le veut, si le solde MédiaMines est suffisant.
- comme l'a dit @Maxence-Leroy, trouver un système pour inciter les gens à identifier. Peut être un tableau de scores des meilleurs identificateurs ? Mais dans ce cas il faudrait probablement prévoir un système de signalement et de ban pour ceux qui trollent et font de fausse identifications. En tout cas c'est important, pour que sur chaque profil on puisse voir sur quelles photos il est.

Ensuite est-ce qu'on garde le système de likes ? Actuellement il n'est pas très utile, mais ça peut être sympa d'afficher qui a liké, ou bien la liste des photos likées par chaque personne. Dans le même esprit, est-ce qu'on rajoute une fonction de commentaires ? Ça peut être drôle, mais ça rajoute encore du travail, et même si tout le monde n'est pas sur facebook, le portail n'a pas forcément vocation à devenir un réseau social comme facebook (surtout que médiamine y poste déjà ses photos).
