### ISSUE TITLE
Billetterie BDA

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#7]
Intégrer le site du BDA (dont réservation des billets) au sein du portail.
A discuter avec le bureau mais je crois que dans l'idée ils sont pour.

**Comment by Maxence-Leroy** [comment]
Fusion avec #4 non ?

**Comment by abocquet** [comment]
Autant pour moi, je n'avais pas vu #4, oui on merge :-)
