### ISSUE TITLE
ApiService is redundant with angular proxy system

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#76]
The ApiService is used for every ajax call. It was originally design to allow requests to the server without specifying its address. It turns out this functionality is built in [angular proxy system](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md) and should be removed. 
However we should wait to have slightly less branches before changing this

**Comment by FlorianVeaux** [comment]
Hi !

I don't agree with you here
- ApiService already allows more than that (authenticate, logout, getCurrentUser) and we should add more features to it in the future.
- The proxy system seems to work only with the webpack dev server, and is not used with `ng build` (see issue 2969 from angular-cli). In that cas, no chance to use it on production
