### ISSUE TITLE
RER B timetable

### ISSUE THREAD

**Issue by abocquet** [Mines-Paristech-Students/Portail-des-eleves#9]
A intégrer sous forme de widget sur la page d'accueil ?

**Comment by gl-mr** [comment]
Salut @abocquet, je suis un ancien élève de l'école travaillant chez Citymapper, fais-moi signe si je peux aider.

**Comment by abocquet** [comment]
Salut @gl-mr, cool de voir que des anciens s'intéresser aussi au projet ! 

On avait classé la feature dans la phase 3 donc on ne s'y est pas encore intéressés en détail mais on avait évoqué la possibilité de d'aller chercher les informations sur l'API de la RATP (qui devrait être en open access), ou sur un tiers-parti (CityMapper par exemple 😉) 

Si tu veux mettre directement les mains dans le code on peut t'orienter vers les ressources pour commencer le projet, sinon si tu as juste des idées à partager on prends aussi 🙂

**Comment by gl-mr** [comment]
Hello @abocquet, je connais très bien l'API RATP, ce n'est pas la plus facile à utiliser mais je veux bien vous donner un coup de pouce.

**Comment by abocquet** [comment]
On n'a pas des ambitions démesurées pour cette fonctionnalité. L'idée c'était simplement d'avoir les horaires à venir du RER B à Luxembourg et/ou Port-Royal

Je te laisse voir sur [le wiki](https://github.com/Mines-Paristech-Students/Portail-des-eleves/wiki) si tu veux commencer à coder. Pour les détails de la méthode de travail je te propose de passer en MP ou sur le slack de l'équipe 🙂

**Comment by abocquet** [comment]
I push the base code in a new branch : https://github.com/Mines-Paristech-Students/Portail-des-eleves/tree/abocquet/rer-timetable
You can put your code in ```rer/views.py```
